### ISSUE TITLE
Bug with even number k's, bug with reverse complements 

### ISSUE THREAD

**Issue by yangkl96** [alexpreynolds/kmer-counter#4]
Issue 1: When I use an even number k with --no_rc, I get more kmer counts than I expect. For example, using a 145bp sequence with k=4, I expect 142 counts. But different 145bp sequences get different counts; one might have 143, another 144

Issue 2: Even when using --no_rc for k=5, I was still returned columns with reverse complements. I had to merge them in python myself

**Comment by alexpreynolds** [comment]
Can you please provide input and runtime statements? Thanks!

**Comment by yangkl96** [comment]
Here is a small subset of the whole fasta I am using:
>H1hesc_1_94_0_chr18_11851975
AATCTGGAGAAGATTTCTGCTTTGATGGACAAATTCGAGCACCAGTTTGA
GACTCTGGACGTCCAGACGCAGCAAATGGAAGACACGATGAGCAGCACGA
CGACGCTCACCACTCCCCAGAACCAAGTGGATATGCTGCTCCAGG
>H1hesc_1_94_1_chr18_11851975
GGAGAAGATTTCTGCTTTGATGGACAAATTCGAGCACCAGTTTGAGACTC
TGGACGTCCAGACGCAGCAAATGGAAGACACGATGAGCAGCACGACGACG
CTCACCACTCCCCAGAACCAAGTGGATATGCTGCTCCAGGAAATG
>H1hesc_1_94_2_chr18_11851975
AGATTTCTGCTTTGATGGACAAATTCGAGCACCAGTTTGAGACTCTGGAC
GTCCAGACGCAGCAAATGGAAGACACGATGAGCAGCACGACGACGCTCAC
CACTCCCCAGAACCAAGTGGATATGCTGCTCCAGGAAATGGCAGA

For issue 1, I get this:
`kmer-counter/kmer-counter --k=2 --no-rc --fasta subset.fa
>H1hesc_1_94_0_chr18_11851975   TG:25 TT:16 GC:17 GT:16 TA:1 AT:15 CC:14 CG:13 TC:26 AG:22
>H1hesc_1_94_1_chr18_11851975   TG:25 CT:21 TT:17 GC:18 GT:16 TA:2 AT:16 CC:14 CG:14 TC:26
>H1hesc_1_94_2_chr18_11851975   TG:26 CT:21 TT:16 GC:20 GT:16 TA:2 AT:16 CC:14 CG:14 TC:25
`

Sum of each row is 165, 169, 170, respectively. But my sequences are only 145bp

For issue 2, I did this:
`kmer-counter/kmer-counter --k=5 --no-rc --fasta fasta.fa > rc_issue.txt`

I got this output. AAAAA and TTTTT are both present, even though they are reverse complements
[rc_issue.txt](https://github.com/alexpreynolds/kmer-counter/files/3444424/rc_issue.txt)

**Comment by alexpreynolds** [comment]
Thank you for the follow-up. I apologize, but I am not able to repeat your second issue with some simple tests.

```
$ cat > /tmp/issue2.fa
>foo
AAAAAAAAAA
$ ./kmer-counter --k=5 --fasta --no-rc /tmp/issue2.fa 
>foo	TTTTT:6
```

If I remove `--no-rc`, I get back both complemented kmers (as expected):

```
$ ./kmer-counter --k=5 --fasta /tmp/issue2.fa 
>foo	TTTTT:6 AAAAA:6
```

I don't pre-initialize a list of mers to "zero" counts. This is done to conserve memory with the underlying data structure that stores mers. 

So when `--no-rc` is specified, it is possible that a "reverse complement" mer is treated as "canonical" in one record if it is "found" first, but the original non-complemented mer could be treated as "canonical" in another record, because of how processing is done. 

If `--no-rc` is left out, then both mers will be counted, even though one of them is "canonical" and this would lead to double-counting. It's just a matter of preference as to what you call "canonical". Both `AAAAA` and `TTTTT` are representations of the same canonical mer.

If you seeing an issue where one specific FASTA record (one header and its associated sequence) contains both a mer and its reverse complement, even with `--no-rc`, then that would be a bug and it would be very useful to have that specific record to test and explore on. Please feel free to follow up, if that's the case.

I'll try to look into the first issue when I have more time.

**Comment by yangkl96** [comment]
Thanks for looking into this. I see, issue 2 for me was that I had a fasta with several sequences, and like you said, whichever one of the sequences turns up first is counted. It just ended up being a problem when I was trying to train a machine learning model, because I had 2 variables which were the same thing but ended up being treated as two different variables

**Comment by alexpreynolds** [comment]
How this is done is not ideal, certainly. I could look at trying to reset/zero the mer-table between records. This might help alleviate the problem of a canonical kmer "changing" its presentation between records, so that you get a consistent answer that might be more usable for downstream work.

I'll dig into the first issue when I can, and if the above isn't too much work, make that change.

**Comment by alexpreynolds** [comment]
I patched double-counts of palindromic mers in commit 5ff2d56

**Comment by alexpreynolds** [comment]
That patch should solve the first issue you reported.

Now that I've had a chance to look at the code, I'm trying to think about how to deal with the second issue and the best solution I have at this time is to print out a "canonical mer" when `--no-rc` is specified. 

In the example above:

```
>foo
AAAAAAAAAA
```

This would print out something like:

```
$ ./kmer-counter --k=5 --fasta --no-rc /tmp/issue2.fa 
>foo	AAAAA|TTTTT:6
```

However, this could also be valid output, depending on the order in which mers are found:

```
$ ./kmer-counter --k=5 --fasta --no-rc /tmp/issue2.fa 
>foo	TTTTT|AAAAA:6
```

I'll investigate this some more when I have time, but I think in the case where there are multiple FASTA records in one file, I may just leave it up to the end user to write a function that maps a mer to a canonical representation, _e.g._, from the example above, strings `TTTTT` and `AAAAA` would map to the same value in a hash table or a similar data structure.

Thanks again for the bug report!

**Comment by yangkl96** [comment]
Thank you for working on this!
